#!/bin/sh
set -e

PKG=pr2-repo

case "$1" in
  configure)
	if [ -e /etc/apt/pr2-packages.key ]; then
	    apt-key add /etc/apt/pr2-packages.key
	fi

        . /etc/lsb-release
        
        echo "deb http://packages.clearpathrobotics.com/pr2-releases/pr2-0.8.0/ubuntu ${DISTRIB_CODENAME} main" > /etc/apt/sources.list.d/pr2debs.list
    ;;

  *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#
